name: Build APK
run-name: Build GuoApp ${{ inputs.build_flags }}
on:
  workflow_dispatch:
    inputs:
      build_flags:
        description: 编译参数 --all-sources 代表真果鉴，留空=红果鉴
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android APK
        run: |
          if [ -z "${{ inputs.build_flags }}" ]; then
            flutter build apk
          else
            flutter build apk --dart-define=BUILD_FLAGS=${{ inputs.build_flags }}
          fi
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
flutter build apk --dart-define=BUILD_FLAGS=--all-sources
